import React from 'react';
import ReactDOM from 'react-dom';
import { Router, Route, browserHistory } from 'react-router';
import App from './pages/App/App';
import Dashboard from './pages/Dashboard/Dashboard';
import Note from './pages/Note/Note';
import NoteEdit from './pages/Dashboard/NoteEdit/NoteEdit';
import Starred from './pages/Starred/Starred';
import Nikkei from './pages/Nikkei/Nikkei';
// import Usdjpy from './pages/Usdjpy/Usdjpy';

// ReactDOM.render((
//   <Router history={browserHistory}>
//     <Route component={App}>
//       <Route path="/" component={Dashboard}>
//         <Route path="notes/:id/edit" component={NoteEdit} />
//       </Route>
//       <Route path="notes/:id" component={Note} />
//       <Route path="starred" component={Starred} />
//     </Route>
//   </Router>

// ), document.getElementById('app'));

ReactDOM.render((
  <Router history={browserHistory}>
   <Route component={App}>
    <Route path="/" component={Dashboard}>
      <Route path="Nikkei" component={NoteEdit} />
      <Route path="Usdjpy" component={Usdjpy} />
      <Route path="Nikkei" component={NoteEdit} />
    </Route>
   </Route>
  </Router>
  
  ),document.getElementById('app'));

// var Comment = React.createClass({
//   rawMarkup: function() {
//     var md = new Remarkable();
//     var rawMarkup = md.render(this.props.children.toString());
//     return { __html: rawMarkup };
//   },

//   render: function() {
//     return (
//       <div className="comment">
//         <h2 className="commentAuthor">
//           {this.props.author}
//         </h2>
//         <span dangerouslySetInnerHTML={this.rawMarkup()} />
//       </div>
//     );
//   }
// });

var CommentBox = React.createClass({
  loadCommentsFromServer: function() {
    // var stocks = this.state.data;
    // stock.id = Date.now();
    $.ajax({
      // url: 'http://apilayer.net/api/live?access_key='+this.props.userName+'&currencies=EUR,GBP,CAD,PLN&source=USD',
      url:'https://finance.google.com/finance/getprices?q=6420&p=1Y&f=d,c,v,o,h,l&ei=4rrIWJHoIYya0QS1i4IQ',
      dataType: 'json',
      // data:stock,
      cache: false,
      success: function(data) {
        this.setState({data: data});
      }.bind(this),
      error: function(xhr, status, err) {
        console.error(this.props.url, status, err.toString());
      }.bind(this)
    });
  },
  // handleCommentSubmit: function(comment) {
  //   var comments = this.state.data;
  //   // Optimistically set an id on the new comment. It will be replaced by an
  //   // id generated by the server. In a production application you would likely
  //   // not use Date.now() for this and would have a more robust system in place.
  //   comment.id = Date.now();
  //   var newComments = comments.concat([comment]);
  //   this.setState({data: newComments});
  //   $.ajax({
  //     url: this.props.url,
  //     dataType: 'json',
  //     // type: 'POST',
  //     data: comment,
  //     success: function(data) {
  //       this.setState({data: data});
  //     }.bind(this),
  //     error: function(xhr, status, err) {
  //       this.setState({data: comments});
  //       console.error(this.props.url, status, err.toString());
  //     }.bind(this)
  //   });
  // },
  getInitialState: function() {
    return {data: []};
  },
  componentDidMount: function() {
    this.loadCommentsFromServer();
    setInterval(this.loadCommentsFromServer, this.props.pollInterval);
  },
  // componentDidMount: function(){
  
  // },
  render: function() {
    return (
      <div className="commentBox">
        <h1>Comments</h1>
      </div>
    );
  },
  // render: function(){
  //   var site = this.state.site
  //   return(
  //     <div>
  //     <div>
  //       // {site}
  //     </div>
  //     // <div>
  //     //   {site.description}
  //     // </div>
  //     </div>
  //     );
  // }
});

ReactDOM.render(
  <CommentBox url="/api/comments.json" pollInterval={2000} />,
  document.getElementById('content')
);
// ReactDOM.render(
//   <CommentBox userName="https://finance.google.com/finance/getprices?q=6420&p=1Y&f=d,c,v,o,h,l&ei=4rrIWJHoIYya0QS1i4IQ" pollInterval={2000} />,
//   document.getElementById('content')
// );

